title: 有趣的技术实践分享
subtitle: JIeJaitt's Blog
description: ''
keywords: null
author: JIeJaitt
language: zh-CN
timezone: ''
url: https://blog.jiejaitt.top
root: /
permalink: posts/:abbrlink.html
abbrlink:
  alg: crc32
  rep: hex
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 7
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 7
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: browser-sync
  port: 4000
feed:
  type: rss2
  path: rss2.xml
  limit: false
  hub: null
lazyload:
  enable: true
  onlypost: true
  loadingImg: null
  isSPA: false
  preloadRatio: 3
filter_optimize:
  enable: true
  # remove the surrounding comments in each of the bundled files
  remove_comments: true
  css:
    # minify all css files
    minify: true
    # bundle loaded css files into one
    bundle: true
    # use a script block to load css elements dynamically
    delivery: true
    # make specific css content inline into the html page
    #   - only support the full path
    #   - default is ['css/main.css']
    inlines:
    excludes:
  js:
    # minify all js files
    minify: true
    # bundle loaded js files into one
    bundle: false
    excludes:
  # set the priority of this plugin,
  # lower means it will be executed first, default of Hexo is 10
  priority: 12