version: 6.0.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name: 
        short_name: 
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        导航: /links
        关于: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/JIeJaitt
        Discuss on GitHub:
            icon: fas fa-comments
            url: 'https://github.com/ppoffice/hexo-theme-icarus/discussions'
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/JIeJaitt
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
comment:
    type: gitalk
    client_id: '232dcb704588214d213c'
    client_secret: '839c0eaa6aea55a641a678488944a0f8cac45cfe'
    repo: 'jiejaitt.github.io'
    owner: 'JIeJaitt'
    admin:
        - JIeJaitt
    per_page: 7                    # 可选填
    distraction_free_mode: false    # 可选填
    pager_direction: last           # 可选填
    create_issue_manually: false    # 可选填
    proxy:                          # 可选填
    flip_move_options:              # 可选填
    enable_hotkey: true             # 可选填
    language: zh-CN                 # 可选填
donates:
    # -
    #     type: afdian
    #     url: ''
    -
        type: alipay
        qrcode: 'https://pic.imgdb.cn/item/611266d05132923bf8a1d198.jpg'
    # -
    #     type: buymeacoffee
    #     url: ''
    # -
    #     type: patreon
    #     url: ''
    # -
    #     type: paypal
    #     business: ''
    #     currency_code: USD
    -
        type: wechat
        qrcode: 'https://pic.imgdb.cn/item/6112669d5132923bf8a16e7d.jpg'
# share:
#     type: sharethis
#     install_url: ''
sidebar:
    left:
        sticky: true
    right:
        sticky: true

widgets:
    -
        position: left
        type: profile
        author: JIeJaitt
        author_title: a student
        location: in your heart
        avatar: /gallery/avatar/0d4ca8488bcca69fb351166a8eb00465.png
        avatar_rounded: true
        gravatar: 
        follow_link: https://github.com/jiejaitt
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/jiejaitt
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com/jiejaitt
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com/jiejaitt
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com/jiejaitt
            RSS:
                icon: fas fa-rss
                url: https://jiejaitt.github.io/rss2.xml
    -
        position: right
        type: toc
        index: true
        collapsed: true
        depth: 3
    -
        position: left
        type: links
        links:
            Icarus: https://blog.jiejaitt.tech
            Handsome: https://jiejaitt.now.cc
            NotionNext: https://anime.jiejaitt.top
            AnimeNav: https://anime.jiejaitt.top
    -
        position: left
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: archives
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true
    # -
    #     position: left
    #     type: subscribe_email
    #     description: 
    #     feedburner_id: ''
    # -
    #     position: left
    #     type: adsense
    #     client_id: ''
    #     slot_id: ''
    # -
    #     position: left
    #     type: followit
    #     description: 
    #     action_url: ''
    #     verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    # cookie_consent:
    #     type: info
    #     theme: edgeless
    #     static: false
    #     position: bottom-left
    #     policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: true
    mathjax: true
    outdated_browser: true
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 

providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
